# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: app

# The type of the application to build.
type: php:7.1
build:
    flavor: composer

variables:
    env:
        from_app: foo
    php:
        # Turn display errors off when you're ready to launch.
        display_errors: On

# The size of the persistent disk of the application (in MB).
disk: 1024

# The mounts that will be performed when the package is deployed.
mounts:
    # A small placeholder scratch space if needed.
    "/storage": "shared:files/storage"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "web"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"

